export interface Nicho {
  id: string;
  nombre: string;
  categoria: string;
  rpmMin: number;
  rpmMax: number;
  gananciasMin: number; // USD/mes con 100k vistas
  gananciasMax: number;
  competencia: "baja" | "media" | "alta";
  tendencia: "subiendo" | "estable" | "bajando";
  faceless: boolean;
  idioma: "español" | "ingles" | "ambos";
  keywords: string[];
  descripcion: string;
  ejemploCanal: string;
  vistasPromedio: string;
  tipo: "long" | "short" | "ambos";
  rank?: number; // ranking position (1-100)
}

export const nichos: Nicho[] = [
  // FINANZAS
  {
    id: "finanzas-personales",
    nombre: "Finanzas Personales",
    categoria: "Finanzas",
    rpmMin: 8, rpmMax: 18,
    gananciasMin: 800, gananciasMax: 1800,
    competencia: "alta", tendencia: "estable", faceless: true,
    idioma: "ambos",
    keywords: ["ahorro dinero", "inversiones", "presupuesto personal", "deudas"],
    descripcion: "Consejos de ahorro, inversión y gestión del dinero personal.",
    ejemploCanal: "Mucho Dinero",
    vistasPromedio: "200K-2M",
    tipo: "long", rank: 6,
  },
  {
    id: "criptomonedas",
    nombre: "Criptomonedas",
    categoria: "Finanzas",
    rpmMin: 12, rpmMax: 25,
    gananciasMin: 1200, gananciasMax: 2500,
    competencia: "alta", tendencia: "subiendo", faceless: true,
    idioma: "ambos",
    keywords: ["bitcoin", "ethereum", "crypto", "defi", "trading crypto"],
    descripcion: "Análisis de criptomonedas, trading y proyectos blockchain.",
    ejemploCanal: "Criptotendencia",
    vistasPromedio: "50K-500K",
    tipo: "long", rank: 3,
  },
  {
    id: "inversiones-bolsa",
    nombre: "Inversiones y Bolsa",
    categoria: "Finanzas",
    rpmMin: 10, rpmMax: 22,
    gananciasMin: 1000, gananciasMax: 2200,
    competencia: "media", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["acciones", "ETF", "dividendos", "S&P 500", "inversión pasiva"],
    descripcion: "Guías de inversión en bolsa, ETFs y estrategias de largo plazo.",
    ejemploCanal: "InvertirSimple",
    vistasPromedio: "30K-300K",
    tipo: "long", rank: 5,
  },
  {
    id: "ingresos-pasivos",
    nombre: "Ingresos Pasivos",
    categoria: "Finanzas",
    rpmMin: 7, rpmMax: 15,
    gananciasMin: 700, gananciasMax: 1500,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["ingresos pasivos", "ganar dinero online", "negocio digital", "renta pasiva"],
    descripcion: "Ideas y estrategias para generar ingresos sin trabajar activamente.",
    ejemploCanal: "Libertad Financiera",
    vistasPromedio: "50K-800K",
    tipo: "long", rank: 9,
  },

  // TECNOLOGÍA & IA
  {
    id: "inteligencia-artificial",
    nombre: "Inteligencia Artificial",
    categoria: "Tecnología",
    rpmMin: 6, rpmMax: 14,
    gananciasMin: 600, gananciasMax: 1400,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "ambos",
    keywords: ["ChatGPT", "IA herramientas", "inteligencia artificial", "automatización IA"],
    descripcion: "Tutoriales y noticias sobre IA, ChatGPT y herramientas de automatización.",
    ejemploCanal: "IA Explicada",
    vistasPromedio: "20K-500K",
    tipo: "long", rank: 12,
  },
  {
    id: "programacion",
    nombre: "Programación y Código",
    categoria: "Tecnología",
    rpmMin: 5, rpmMax: 12,
    gananciasMin: 500, gananciasMax: 1200,
    competencia: "alta", tendencia: "estable", faceless: true,
    idioma: "ambos",
    keywords: ["aprender programar", "Python", "JavaScript", "desarrollo web", "coding"],
    descripcion: "Tutoriales de programación, desarrollo web y software.",
    ejemploCanal: "Midudev",
    vistasPromedio: "10K-200K",
    tipo: "long", rank: 16,
  },
  {
    id: "gadgets-tecnologia",
    nombre: "Gadgets y Reviews Tech",
    categoria: "Tecnología",
    rpmMin: 4, rpmMax: 10,
    gananciasMin: 400, gananciasMax: 1000,
    competencia: "alta", tendencia: "estable", faceless: false,
    idioma: "español",
    keywords: ["review iPhone", "mejores auriculares", "tecnología 2024", "unboxing"],
    descripcion: "Reviews de smartphones, laptops, gadgets y accesorios tech.",
    ejemploCanal: "El Androide Feliz",
    vistasPromedio: "50K-1M",
    tipo: "long", rank: 22,
  },
  {
    id: "automatizacion-negocios",
    nombre: "Automatización de Negocios",
    categoria: "Tecnología",
    rpmMin: 8, rpmMax: 20,
    gananciasMin: 800, gananciasMax: 2000,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "ambos",
    keywords: ["make.com", "zapier", "n8n", "automatización", "no-code"],
    descripcion: "Automatización de procesos con herramientas no-code e IA.",
    ejemploCanal: "AutomatizaTu",
    vistasPromedio: "5K-100K",
    tipo: "long", rank: 7,
  },

  // SALUD & FITNESS
  {
    id: "fitness-gym",
    nombre: "Fitness y Gym",
    categoria: "Salud",
    rpmMin: 3, rpmMax: 8,
    gananciasMin: 300, gananciasMax: 800,
    competencia: "alta", tendencia: "estable", faceless: false,
    idioma: "español",
    keywords: ["rutina gym", "perder peso", "ganar músculo", "ejercicios casa"],
    descripcion: "Rutinas de ejercicio, nutrición deportiva y consejos de gym.",
    ejemploCanal: "Gymtopics",
    vistasPromedio: "50K-2M",
    tipo: "ambos", rank: 30,
  },
  {
    id: "salud-mental",
    nombre: "Salud Mental",
    categoria: "Salud",
    rpmMin: 4, rpmMax: 10,
    gananciasMin: 400, gananciasMax: 1000,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["ansiedad", "depresión", "mindfulness", "psicología", "bienestar mental"],
    descripcion: "Contenido sobre salud mental, psicología y bienestar emocional.",
    ejemploCanal: "Entiende Tu Mente",
    vistasPromedio: "30K-500K",
    tipo: "long", rank: 20,
  },
  {
    id: "nutricion-dieta",
    nombre: "Nutrición y Dieta",
    categoria: "Salud",
    rpmMin: 4, rpmMax: 9,
    gananciasMin: 400, gananciasMax: 900,
    competencia: "alta", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["dieta saludable", "recetas sanas", "bajar de peso", "alimentación"],
    descripcion: "Planes alimenticios, recetas saludables y consejos nutricionales.",
    ejemploCanal: "NutricionConMarta",
    vistasPromedio: "20K-300K",
    tipo: "long", rank: 24,
  },
  {
    id: "meditacion",
    nombre: "Meditación y Mindfulness",
    categoria: "Salud",
    rpmMin: 3, rpmMax: 7,
    gananciasMin: 300, gananciasMax: 700,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "ambos",
    keywords: ["meditación guiada", "mindfulness", "relajación", "yoga"],
    descripcion: "Meditaciones guiadas, técnicas de relajación y mindfulness.",
    ejemploCanal: "Meditación Shakti",
    vistasPromedio: "10K-200K",
    tipo: "ambos", rank: 35,
  },

  // NEGOCIOS & EMPRENDIMIENTO
  {
    id: "emprendimiento",
    nombre: "Emprendimiento Digital",
    categoria: "Negocios",
    rpmMin: 6, rpmMax: 14,
    gananciasMin: 600, gananciasMax: 1400,
    competencia: "alta", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["emprender", "negocio online", "startup", "ecommerce", "dropshipping"],
    descripcion: "Ideas de negocio, estrategias de emprendimiento y casos de éxito.",
    ejemploCanal: "Juan Lombana",
    vistasPromedio: "30K-1M",
    tipo: "long", rank: 13,
  },
  {
    id: "marketing-digital",
    nombre: "Marketing Digital",
    categoria: "Negocios",
    rpmMin: 7, rpmMax: 16,
    gananciasMin: 700, gananciasMax: 1600,
    competencia: "alta", tendencia: "estable", faceless: true,
    idioma: "ambos",
    keywords: ["SEO", "redes sociales", "email marketing", "publicidad digital", "funnels"],
    descripcion: "Estrategias de marketing digital, SEO y publicidad online.",
    ejemploCanal: "Vilma Núñez",
    vistasPromedio: "20K-500K",
    tipo: "long", rank: 11,
  },
  {
    id: "dropshipping",
    nombre: "Dropshipping y E-commerce",
    categoria: "Negocios",
    rpmMin: 5, rpmMax: 13,
    gananciasMin: 500, gananciasMax: 1300,
    competencia: "media", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["dropshipping", "shopify", "tienda online", "vender amazon", "aliexpress"],
    descripcion: "Guías de dropshipping, Shopify y cómo crear tiendas online.",
    ejemploCanal: "Dropshipping España",
    vistasPromedio: "15K-200K",
    tipo: "long", rank: 15,
  },
  {
    id: "freelancing",
    nombre: "Freelancing y Trabajo Remoto",
    categoria: "Negocios",
    rpmMin: 5, rpmMax: 11,
    gananciasMin: 500, gananciasMax: 1100,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["trabajo remoto", "freelancer", "upwork", "fiverr", "trabajar desde casa"],
    descripcion: "Cómo conseguir clientes como freelancer y trabajar remotamente.",
    ejemploCanal: "Freelance en Español",
    vistasPromedio: "10K-150K",
    tipo: "long", rank: 18,
  },

  // ENTRETENIMIENTO & LIFESTYLE
  {
    id: "true-crime",
    nombre: "True Crime en Español",
    categoria: "Entretenimiento",
    rpmMin: 2, rpmMax: 6,
    gananciasMin: 200, gananciasMax: 600,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["crímenes reales", "misterios", "casos sin resolver", "documental crimen"],
    descripcion: "Narración de crímenes reales, misterios y casos policiales.",
    ejemploCanal: "Crímenes del Pasado",
    vistasPromedio: "20K-500K",
    tipo: "long", rank: 38,
  },
  {
    id: "historia",
    nombre: "Historia y Documentales",
    categoria: "Entretenimiento",
    rpmMin: 3, rpmMax: 8,
    gananciasMin: 300, gananciasMax: 800,
    competencia: "baja", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["historia mundial", "guerras", "civilizaciones antiguas", "documental historia"],
    descripcion: "Documentales y narraciones históricas en formato entretenido.",
    ejemploCanal: "DrossRotzank",
    vistasPromedio: "30K-2M",
    tipo: "long", rank: 27,
  },
  {
    id: "misterios-conspiraciones",
    nombre: "Misterios y Conspiraciones",
    categoria: "Entretenimiento",
    rpmMin: 2, rpmMax: 5,
    gananciasMin: 200, gananciasMax: 500,
    competencia: "baja", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["conspiraciones", "misterios sin resolver", "fenómenos extraños", "ovnis"],
    descripcion: "Teorías de conspiración, misterios y fenómenos inexplicables.",
    ejemploCanal: "Destripando la Historia",
    vistasPromedio: "20K-400K",
    tipo: "long", rank: 44,
  },
  {
    id: "viajes",
    nombre: "Viajes y Turismo",
    categoria: "Lifestyle",
    rpmMin: 3, rpmMax: 8,
    gananciasMin: 300, gananciasMax: 800,
    competencia: "media", tendencia: "subiendo", faceless: false,
    idioma: "español",
    keywords: ["viajes baratos", "guía de viaje", "mochilero", "turismo", "mejores destinos"],
    descripcion: "Guías de viaje, destinos y consejos para viajar con poco presupuesto.",
    ejemploCanal: "Viaja y Descubre",
    vistasPromedio: "20K-300K",
    tipo: "long", rank: 29,
  },
  {
    id: "cocina-recetas",
    nombre: "Cocina y Recetas",
    categoria: "Lifestyle",
    rpmMin: 2, rpmMax: 6,
    gananciasMin: 200, gananciasMax: 600,
    competencia: "alta", tendencia: "estable", faceless: false,
    idioma: "español",
    keywords: ["recetas fáciles", "cocina casera", "postres", "comida rápida"],
    descripcion: "Recetas de cocina, tutoriales gastronómicos y tips culinarios.",
    ejemploCanal: "Directo al Paladar",
    vistasPromedio: "30K-500K",
    tipo: "ambos", rank: 42,
  },

  // GAMING
  {
    id: "gaming-tutoriales",
    nombre: "Gaming Tutoriales",
    categoria: "Gaming",
    rpmMin: 2, rpmMax: 5,
    gananciasMin: 200, gananciasMax: 500,
    competencia: "alta", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["trucos videojuegos", "guías gaming", "walkthroughs", "cheats"],
    descripcion: "Guías, trucos y tutoriales de videojuegos populares.",
    ejemploCanal: "VidaExtra",
    vistasPromedio: "20K-500K",
    tipo: "long", rank: 46,
  },
  {
    id: "minecraft",
    nombre: "Minecraft",
    categoria: "Gaming",
    rpmMin: 2, rpmMax: 4,
    gananciasMin: 200, gananciasMax: 400,
    competencia: "alta", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["minecraft survival", "builds minecraft", "mods minecraft", "servidor minecraft"],
    descripcion: "Contenido de Minecraft: survival, builds, mods y servidores.",
    ejemploCanal: "Vegetta777",
    vistasPromedio: "50K-2M",
    tipo: "ambos", rank: 55,
  },
  {
    id: "retro-gaming",
    nombre: "Retro Gaming",
    categoria: "Gaming",
    rpmMin: 3, rpmMax: 7,
    gananciasMin: 300, gananciasMax: 700,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["juegos clásicos", "retro consolas", "nostalgia gaming", "años 90 videojuegos"],
    descripcion: "Análisis y nostalgia de videojuegos y consolas retro.",
    ejemploCanal: "RetroGamer",
    vistasPromedio: "10K-150K",
    tipo: "long", rank: 36,
  },

  // YOUTUBE & REDES SOCIALES
  {
    id: "crecer-youtube",
    nombre: "Crecer en YouTube",
    categoria: "YouTube",
    rpmMin: 4, rpmMax: 10,
    gananciasMin: 400, gananciasMax: 1000,
    competencia: "alta", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["crecer youtube", "algoritmo youtube", "monetizar youtube", "suscriptores"],
    descripcion: "Consejos para crecer en YouTube, ganar suscriptores y monetizar.",
    ejemploCanal: "Crea con Valentín",
    vistasPromedio: "10K-300K",
    tipo: "long", rank: 21,
  },
  {
    id: "canal-faceless",
    nombre: "Canal Faceless / Automatizado",
    categoria: "YouTube",
    rpmMin: 5, rpmMax: 12,
    gananciasMin: 500, gananciasMax: 1200,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["canal faceless", "youtube automatico", "canal sin mostrar cara", "youtube pasivo"],
    descripcion: "Cómo crear y monetizar canales de YouTube sin aparecer en cámara.",
    ejemploCanal: "Faceless España",
    vistasPromedio: "20K-400K",
    tipo: "long", rank: 17,
  },
  {
    id: "tiktok-reels",
    nombre: "TikTok y Reels Virales",
    categoria: "YouTube",
    rpmMin: 2, rpmMax: 5,
    gananciasMin: 200, gananciasMax: 500,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["tiktok viral", "reels instagram", "shorts youtube", "video corto"],
    descripcion: "Estrategias para hacer contenido viral en TikTok, Reels y Shorts.",
    ejemploCanal: "Viral Shorts",
    vistasPromedio: "50K-5M",
    tipo: "short", rank: 8,
  },

  // EDUCACIÓN
  {
    id: "idiomas",
    nombre: "Aprender Idiomas",
    categoria: "Educación",
    rpmMin: 4, rpmMax: 9,
    gananciasMin: 400, gananciasMax: 900,
    competencia: "media", tendencia: "estable", faceless: true,
    idioma: "ambos",
    keywords: ["aprender inglés", "inglés rápido", "gramática inglés", "pronunciación"],
    descripcion: "Cursos y tutoriales para aprender inglés y otros idiomas.",
    ejemploCanal: "Inglés con Juan",
    vistasPromedio: "20K-400K",
    tipo: "long", rank: 25,
  },
  {
    id: "productividad",
    nombre: "Productividad y Hábitos",
    categoria: "Educación",
    rpmMin: 5, rpmMax: 11,
    gananciasMin: 500, gananciasMax: 1100,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["productividad", "hábitos", "rutina mañana", "gestión tiempo", "Notion"],
    descripcion: "Técnicas de productividad, hábitos y organización personal.",
    ejemploCanal: "La Neurona Productiva",
    vistasPromedio: "20K-500K",
    tipo: "long", rank: 19,
  },
  {
    id: "libros-resumenes",
    nombre: "Resúmenes de Libros",
    categoria: "Educación",
    rpmMin: 4, rpmMax: 9,
    gananciasMin: 400, gananciasMax: 900,
    competencia: "baja", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["resumen libro", "libros recomendados", "autoayuda libros", "leer más"],
    descripcion: "Resúmenes y análisis de libros de negocios, autoayuda y desarrollo personal.",
    ejemploCanal: "Libros Para Emprendedores",
    vistasPromedio: "10K-200K",
    tipo: "long", rank: 26,
  },
  {
    id: "filosofia",
    nombre: "Filosofía y Pensamiento",
    categoria: "Educación",
    rpmMin: 3, rpmMax: 8,
    gananciasMin: 300, gananciasMax: 800,
    competencia: "baja", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["filosofía", "estoicismo", "pensamiento crítico", "psicología filosófica"],
    descripcion: "Filosofía práctica, estoicismo y pensamiento crítico aplicado a la vida.",
    ejemploCanal: "La Filosofía en 5 Minutos",
    vistasPromedio: "10K-300K",
    tipo: "long", rank: 32,
  },

  // INGLÉS (alto RPM)
  {
    id: "personal-finance-en",
    nombre: "Personal Finance (English)",
    categoria: "Finanzas",
    rpmMin: 15, rpmMax: 40,
    gananciasMin: 1500, gananciasMax: 4000,
    competencia: "alta", tendencia: "estable", faceless: true,
    idioma: "ingles",
    keywords: ["personal finance", "investing", "stock market", "budget", "retire early"],
    descripcion: "Personal finance, investing and wealth building for English audience.",
    ejemploCanal: "Graham Stephan",
    vistasPromedio: "100K-5M",
    tipo: "long", rank: 1,
  },
  {
    id: "real-estate-en",
    nombre: "Real Estate (English)",
    categoria: "Finanzas",
    rpmMin: 18, rpmMax: 45,
    gananciasMin: 1800, gananciasMax: 4500,
    competencia: "media", tendencia: "estable", faceless: true,
    idioma: "ingles",
    keywords: ["real estate investing", "rental properties", "how to buy house", "BRRRR"],
    descripcion: "Real estate investing strategies for passive income.",
    ejemploCanal: "BiggerPockets",
    vistasPromedio: "30K-500K",
    tipo: "long", rank: 2,
  },
  {
    id: "ai-tools-en",
    nombre: "AI Tools & Tutorials (English)",
    categoria: "Tecnología",
    rpmMin: 8, rpmMax: 18,
    gananciasMin: 800, gananciasMax: 1800,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "ingles",
    keywords: ["ChatGPT tutorial", "AI tools 2024", "make money with AI", "AI automation"],
    descripcion: "Tutorials and news about AI tools for English-speaking audience.",
    ejemploCanal: "Matt Wolfe",
    vistasPromedio: "20K-500K",
    tipo: "long", rank: 8,
  },
  {
    id: "software-tutorials-en",
    nombre: "Software Tutorials (English)",
    categoria: "Tecnología",
    rpmMin: 6, rpmMax: 15,
    gananciasMin: 600, gananciasMax: 1500,
    competencia: "media", tendencia: "estable", faceless: true,
    idioma: "ingles",
    keywords: ["excel tutorial", "photoshop", "video editing", "software how to"],
    descripcion: "Step-by-step software tutorials for professionals.",
    ejemploCanal: "Kevin Stratvert",
    vistasPromedio: "20K-500K",
    tipo: "long", rank: 14,
  },
  {
    id: "health-wellness-en",
    nombre: "Health & Wellness (English)",
    categoria: "Salud",
    rpmMin: 5, rpmMax: 14,
    gananciasMin: 500, gananciasMax: 1400,
    competencia: "alta", tendencia: "subiendo", faceless: true,
    idioma: "ingles",
    keywords: ["weight loss", "healthy eating", "intermittent fasting", "workout"],
    descripcion: "Health tips, fitness and wellness content in English.",
    ejemploCanal: "Dr. Berg",
    vistasPromedio: "50K-2M",
    tipo: "long", rank: 10,
  },

  // NICHOS ESPECIALES (baja competencia)
  {
    id: "ia-para-empresas",
    nombre: "IA para Empresas y Pymes",
    categoria: "Tecnología",
    rpmMin: 10, rpmMax: 22,
    gananciasMin: 1000, gananciasMax: 2200,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["IA empresas", "transformación digital", "automatizar negocio", "ChatGPT empresa"],
    descripcion: "Cómo implementar IA en negocios tradicionales y pymes.",
    ejemploCanal: "IA para Negocios",
    vistasPromedio: "5K-80K",
    tipo: "long", rank: 4,
  },
  {
    id: "trading-forex",
    nombre: "Trading Forex",
    categoria: "Finanzas",
    rpmMin: 10, rpmMax: 25,
    gananciasMin: 1000, gananciasMax: 2500,
    competencia: "media", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["forex trading", "análisis técnico", "pares divisas", "MT4", "scalping"],
    descripcion: "Trading de divisas, análisis técnico y estrategias de Forex.",
    ejemploCanal: "Trading en Español",
    vistasPromedio: "10K-200K",
    tipo: "long", rank: 3,
  },
  {
    id: "bienes-raices",
    nombre: "Bienes Raíces e Inversión",
    categoria: "Finanzas",
    rpmMin: 8, rpmMax: 18,
    gananciasMin: 800, gananciasMax: 1800,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["invertir inmuebles", "comprar casa", "alquiler vacacional", "flipping"],
    descripcion: "Inversión en bienes raíces, compra-venta de propiedades e inmuebles.",
    ejemploCanal: "Inversión Inmobiliaria",
    vistasPromedio: "10K-150K",
    tipo: "long", rank: 6,
  },
  {
    id: "psicologia-relaciones",
    nombre: "Psicología y Relaciones",
    categoria: "Lifestyle",
    rpmMin: 4, rpmMax: 9,
    gananciasMin: 400, gananciasMax: 900,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["psicología relaciones", "amor propio", "relaciones tóxicas", "autoestima"],
    descripcion: "Psicología aplicada a las relaciones, autoestima y bienestar emocional.",
    ejemploCanal: "Psych2Go Español",
    vistasPromedio: "20K-500K",
    tipo: "long", rank: 23,
  },
  {
    id: "derecho-legal",
    nombre: "Consejos Legales y Jurídicos",
    categoria: "Educación",
    rpmMin: 10, rpmMax: 22,
    gananciasMin: 1000, gananciasMax: 2200,
    competencia: "baja", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["derechos del consumidor", "contratos", "asesoría legal", "leyes España"],
    descripcion: "Orientación legal, derechos ciudadanos y casos jurídicos explicados.",
    ejemploCanal: "El Abogado de YouTube",
    vistasPromedio: "5K-100K",
    tipo: "long", rank: 5,
  },
  {
    id: "mascotas",
    nombre: "Mascotas y Animales",
    categoria: "Lifestyle",
    rpmMin: 2, rpmMax: 5,
    gananciasMin: 200, gananciasMax: 500,
    competencia: "media", tendencia: "estable", faceless: false,
    idioma: "español",
    keywords: ["cuidado perros", "entrenamiento mascotas", "gatos", "animales curiosos"],
    descripcion: "Cuidado, entrenamiento y vida con mascotas.",
    ejemploCanal: "Mis Animalitos",
    vistasPromedio: "20K-500K",
    tipo: "long", rank: 47,
  },
  {
    id: "decoracion-hogar",
    nombre: "Decoración y Hogar",
    categoria: "Lifestyle",
    rpmMin: 3, rpmMax: 7,
    gananciasMin: 300, gananciasMax: 700,
    competencia: "media", tendencia: "estable", faceless: false,
    idioma: "español",
    keywords: ["decorar casa", "ideas hogar", "diseño interior", "DIY hogar"],
    descripcion: "Ideas de decoración, diseño de interiores y proyectos DIY para el hogar.",
    ejemploCanal: "Deco Ideas",
    vistasPromedio: "10K-200K",
    tipo: "long", rank: 34,
  },
  {
    id: "podcast-clips",
    nombre: "Clips de Podcast",
    categoria: "Entretenimiento",
    rpmMin: 3, rpmMax: 7,
    gananciasMin: 300, gananciasMax: 700,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["clips podcast", "momentos virales podcast", "cortes entrevistas", "podcast español"],
    descripcion: "Canal de clips virales de podcasts y entrevistas famosas.",
    ejemploCanal: "Clips de Megawhatpodcast",
    vistasPromedio: "10K-500K",
    tipo: "short", rank: 10,
  },
  {
    id: "motivacion",
    nombre: "Motivación y Desarrollo Personal",
    categoria: "Lifestyle",
    rpmMin: 3, rpmMax: 8,
    gananciasMin: 300, gananciasMax: 800,
    competencia: "alta", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["motivación", "superación personal", "éxito", "mentalidad ganadora", "disciplina"],
    descripcion: "Contenido motivacional, historias de éxito y consejos de desarrollo personal.",
    ejemploCanal: "Diario de un Millennial",
    vistasPromedio: "20K-1M",
    tipo: "ambos", rank: 31,
  },

  // ─── NUEVOS NICHOS ─────────────────────────────────────────────

  // RELIGIÓN Y ESPIRITUALIDAD
  {
    id: "profecias-biblicas",
    nombre: "Profecías Bíblicas",
    categoria: "Religión",
    rpmMin: 4, rpmMax: 10,
    gananciasMin: 400, gananciasMax: 1000,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["profecías bíblicas", "apocalipsis", "fin del mundo", "biblia"],
    descripcion: "Análisis de profecías bíblicas, apocalipsis y textos sagrados.",
    ejemploCanal: "Profecías Hoy",
    vistasPromedio: "20K-400K",
    tipo: "long", rank: 28,
  },
  {
    id: "misterios-religiosos",
    nombre: "Misterios Religiosos",
    categoria: "Religión",
    rpmMin: 3, rpmMax: 8,
    gananciasMin: 300, gananciasMax: 800,
    competencia: "media", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["misterios religiosos", "ángeles", "milagros", "fe cristiana"],
    descripcion: "Exploración de misterios, milagros y fenómenos religiosos.",
    ejemploCanal: "Fe y Misterio",
    vistasPromedio: "15K-300K",
    tipo: "long", rank: 33,
  },
  {
    id: "meditacion-mindfulness-nuevo",
    nombre: "Meditación Guiada Avanzada",
    categoria: "Religión",
    rpmMin: 4, rpmMax: 9,
    gananciasMin: 400, gananciasMax: 900,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["meditación guiada", "chakras", "frecuencias", "bienestar espiritual"],
    descripcion: "Meditaciones guiadas avanzadas, frecuencias y bienestar espiritual.",
    ejemploCanal: "Consciencia Plena",
    vistasPromedio: "10K-200K",
    tipo: "long", rank: 37,
  },

  // SALUD Y BIENESTAR (nuevos)
  {
    id: "salud-mental-nuevo",
    nombre: "Salud Mental Profunda",
    categoria: "Salud",
    rpmMin: 5, rpmMax: 11,
    gananciasMin: 500, gananciasMax: 1100,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["salud mental", "terapia online", "psicología práctica", "autocuidado"],
    descripcion: "Psicología práctica, terapia y autocuidado para el bienestar mental.",
    ejemploCanal: "Psicología Al Día",
    vistasPromedio: "20K-400K",
    tipo: "long", rank: 20,
  },
  {
    id: "perdida-peso",
    nombre: "Pérdida de Peso",
    categoria: "Salud",
    rpmMin: 4, rpmMax: 9,
    gananciasMin: 400, gananciasMax: 900,
    competencia: "alta", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["adelgazar", "dieta", "perder barriga", "intermittent fasting"],
    descripcion: "Métodos y estrategias probadas para perder peso de forma saludable.",
    ejemploCanal: "Cuerpo Fit",
    vistasPromedio: "30K-600K",
    tipo: "long", rank: 24,
  },
  {
    id: "medicina-natural",
    nombre: "Medicina Natural y Remedios",
    categoria: "Salud",
    rpmMin: 3, rpmMax: 8,
    gananciasMin: 300, gananciasMax: 800,
    competencia: "media", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["remedios naturales", "plantas medicinales", "medicina alternativa", "cúrcuma"],
    descripcion: "Remedios naturales, plantas medicinales y medicina alternativa.",
    ejemploCanal: "Naturalmente Sano",
    vistasPromedio: "15K-300K",
    tipo: "long", rank: 39,
  },

  // RELACIONES
  {
    id: "psicologia-relaciones-nuevo",
    nombre: "Psicología de las Relaciones",
    categoria: "Relaciones",
    rpmMin: 3, rpmMax: 8,
    gananciasMin: 300, gananciasMax: 800,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["relaciones de pareja", "psicología del amor", "comunicación pareja", "apego"],
    descripcion: "Psicología profunda de las relaciones de pareja y vínculos emocionales.",
    ejemploCanal: "Amor Consciente",
    vistasPromedio: "20K-400K",
    tipo: "long", rank: 30,
  },
  {
    id: "atraer-pareja",
    nombre: "Cómo Atraer Pareja",
    categoria: "Relaciones",
    rpmMin: 2, rpmMax: 7,
    gananciasMin: 200, gananciasMax: 700,
    competencia: "media", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["cómo ligar", "atraer hombres", "atraer mujeres", "lenguaje corporal", "seducción"],
    descripcion: "Consejos de seducción, lenguaje corporal y cómo atraer a una pareja.",
    ejemploCanal: "Atracción Total",
    vistasPromedio: "20K-500K",
    tipo: "long", rank: 43,
  },
  {
    id: "superar-ruptura",
    nombre: "Superar una Ruptura",
    categoria: "Relaciones",
    rpmMin: 2, rpmMax: 6,
    gananciasMin: 200, gananciasMax: 600,
    competencia: "baja", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["superar ruptura", "desamor", "olvidar ex", "sanación emocional"],
    descripcion: "Guías emocionales para superar rupturas amorosas y sanar el corazón.",
    ejemploCanal: "Sana Tu Corazón",
    vistasPromedio: "15K-300K",
    tipo: "long", rank: 50,
  },

  // HISTORIA Y CULTURA
  {
    id: "historia-antigua",
    nombre: "Historia Antigua",
    categoria: "Historia",
    rpmMin: 3, rpmMax: 7,
    gananciasMin: 300, gananciasMax: 700,
    competencia: "baja", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["historia antigua", "Roma", "Grecia", "Egipto", "civilizaciones"],
    descripcion: "Historia de las grandes civilizaciones antiguas: Roma, Grecia, Egipto.",
    ejemploCanal: "Historia Épica",
    vistasPromedio: "20K-400K",
    tipo: "long", rank: 36,
  },
  {
    id: "civilizaciones-perdidas",
    nombre: "Civilizaciones Perdidas",
    categoria: "Historia",
    rpmMin: 3, rpmMax: 8,
    gananciasMin: 300, gananciasMax: 800,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["civilizaciones perdidas", "Atlántida", "mayas", "sumerios", "arqueología"],
    descripcion: "Misterios y descubrimientos sobre civilizaciones desaparecidas.",
    ejemploCanal: "Misterios del Pasado",
    vistasPromedio: "15K-350K",
    tipo: "long", rank: 32,
  },
  {
    id: "guerras-conflictos",
    nombre: "Guerras y Conflictos Históricos",
    categoria: "Historia",
    rpmMin: 3, rpmMax: 7,
    gananciasMin: 300, gananciasMax: 700,
    competencia: "media", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["Segunda Guerra Mundial", "guerras históricas", "batallas", "conflictos bélicos"],
    descripcion: "Análisis detallado de guerras y conflictos que cambiaron el mundo.",
    ejemploCanal: "Guerras del Mundo",
    vistasPromedio: "20K-500K",
    tipo: "long", rank: 38,
  },
  {
    id: "historia-latinoamerica",
    nombre: "Historia de América Latina",
    categoria: "Historia",
    rpmMin: 2, rpmMax: 6,
    gananciasMin: 200, gananciasMax: 600,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["historia latinoamerica", "independencia", "aztecas", "incas", "conquistadores"],
    descripcion: "Historia de los pueblos originarios y la conquista de América Latina.",
    ejemploCanal: "Historia Latina",
    vistasPromedio: "10K-250K",
    tipo: "long", rank: 45,
  },

  // MISTERIO Y PARANORMAL
  {
    id: "ovnis-extraterrestres",
    nombre: "OVNIs y Extraterrestres",
    categoria: "Paranormal",
    rpmMin: 3, rpmMax: 8,
    gananciasMin: 300, gananciasMax: 800,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["ovnis", "extraterrestres", "vida extraterrestre", "fenómeno OVNI", "UAP"],
    descripcion: "Investigaciones sobre OVNIs, fenómenos UAP y vida extraterrestre.",
    ejemploCanal: "Tercer Milenio",
    vistasPromedio: "15K-400K",
    tipo: "long", rank: 34,
  },
  {
    id: "fenomenos-inexplicables",
    nombre: "Fenómenos Inexplicables",
    categoria: "Paranormal",
    rpmMin: 3, rpmMax: 7,
    gananciasMin: 300, gananciasMax: 700,
    competencia: "baja", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["fenómenos paranormales", "lo inexplicable", "misterios sin resolver", "ciencia rara"],
    descripcion: "Análisis de fenómenos paranormales, misterios sin resolver y lo inexplicable.",
    ejemploCanal: "Lo Imposible",
    vistasPromedio: "10K-300K",
    tipo: "long", rank: 40,
  },
  {
    id: "conspiraciones",
    nombre: "Teorías de Conspiración",
    categoria: "Paranormal",
    rpmMin: 2, rpmMax: 7,
    gananciasMin: 200, gananciasMax: 700,
    competencia: "media", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["conspiraciones", "illuminati", "new world order", "gobierno secreto", "teorías"],
    descripcion: "Exploración de teorías de conspiración populares y secretos del poder.",
    ejemploCanal: "La Verdad Oculta",
    vistasPromedio: "15K-400K",
    tipo: "long", rank: 44,
  },

  // NEGOCIOS Y EMPRENDIMIENTO (nuevos)
  {
    id: "dropshipping-nuevo",
    nombre: "Dropshipping Avanzado",
    categoria: "Negocios",
    rpmMin: 5, rpmMax: 14,
    gananciasMin: 500, gananciasMax: 1400,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["dropshipping 2025", "shopify avanzado", "productos ganadores", "fb ads ecom"],
    descripcion: "Estrategias avanzadas de dropshipping, productos ganadores y anuncios.",
    ejemploCanal: "Dropshipping Pro",
    vistasPromedio: "10K-200K",
    tipo: "long", rank: 15,
  },
  {
    id: "print-on-demand",
    nombre: "Print on Demand",
    categoria: "Negocios",
    rpmMin: 4, rpmMax: 12,
    gananciasMin: 400, gananciasMax: 1200,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["print on demand", "Merch by Amazon", "Redbubble", "Printful", "diseños"],
    descripcion: "Cómo ganar dinero con impresión bajo demanda sin inventario.",
    ejemploCanal: "POD Español",
    vistasPromedio: "8K-150K",
    tipo: "long", rank: 18,
  },
  {
    id: "freelancing-nuevo",
    nombre: "Freelancing Digital",
    categoria: "Negocios",
    rpmMin: 4, rpmMax: 11,
    gananciasMin: 400, gananciasMax: 1100,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["freelancer digital", "servicios online", "clientes freelance", "portafolio"],
    descripcion: "Cómo construir una carrera freelance exitosa ofreciendo servicios digitales.",
    ejemploCanal: "Freelancer Libre",
    vistasPromedio: "8K-150K",
    tipo: "long", rank: 22,
  },
  {
    id: "amazon-fba",
    nombre: "Amazon FBA",
    categoria: "Negocios",
    rpmMin: 6, rpmMax: 16,
    gananciasMin: 600, gananciasMax: 1600,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["Amazon FBA", "vender en Amazon", "private label", "Amazon seller", "FBA España"],
    descripcion: "Cómo vender en Amazon con FBA, private label y estrategias de escalado.",
    ejemploCanal: "Amazon FBA Español",
    vistasPromedio: "10K-180K",
    tipo: "long", rank: 11,
  },
  {
    id: "youtube-negocio",
    nombre: "YouTube como Negocio",
    categoria: "Negocios",
    rpmMin: 5, rpmMax: 13,
    gananciasMin: 500, gananciasMax: 1300,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["YouTube negocio", "monetizar YouTube", "ingresos YouTube", "canal rentable"],
    descripcion: "Cómo convertir tu canal de YouTube en un negocio rentable y escalable.",
    ejemploCanal: "YouTube Business",
    vistasPromedio: "10K-250K",
    tipo: "long", rank: 16,
  },

  // EDUCACIÓN (nuevos)
  {
    id: "aprender-ingles",
    nombre: "Aprender Inglés",
    categoria: "Educación",
    rpmMin: 3, rpmMax: 8,
    gananciasMin: 300, gananciasMax: 800,
    competencia: "alta", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["aprender inglés", "inglés desde cero", "inglés para trabajo", "hablar inglés"],
    descripcion: "Cursos completos para aprender inglés desde cero de forma práctica.",
    ejemploCanal: "Inglés Total",
    vistasPromedio: "20K-500K",
    tipo: "long", rank: 29,
  },
  {
    id: "productividad-estudiantil",
    nombre: "Productividad Estudiantil",
    categoria: "Educación",
    rpmMin: 3, rpmMax: 7,
    gananciasMin: 300, gananciasMax: 700,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["estudiar mejor", "técnicas estudio", "memoria", "notas universitarias"],
    descripcion: "Técnicas de estudio, memoria y productividad para estudiantes.",
    ejemploCanal: "Estudia Mejor",
    vistasPromedio: "15K-300K",
    tipo: "long", rank: 37,
  },
  {
    id: "preparacion-universitaria",
    nombre: "Preparación Universitaria",
    categoria: "Educación",
    rpmMin: 3, rpmMax: 7,
    gananciasMin: 300, gananciasMax: 700,
    competencia: "baja", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["universidad", "oposiciones", "examen universitario", "carrera universitaria"],
    descripcion: "Guías para preparar exámenes universitarios, oposiciones y selectividad.",
    ejemploCanal: "Aprueba Ya",
    vistasPromedio: "10K-200K",
    tipo: "long", rank: 42,
  },

  // VIAJES
  {
    id: "viajes-economicos",
    nombre: "Viajes Económicos",
    categoria: "Viajes",
    rpmMin: 3, rpmMax: 8,
    gananciasMin: 300, gananciasMax: 800,
    competencia: "media", tendencia: "subiendo", faceless: false,
    idioma: "español",
    keywords: ["viajes baratos", "vuelos low cost", "hoteles económicos", "mochilero"],
    descripcion: "Cómo viajar por el mundo gastando lo mínimo con consejos prácticos.",
    ejemploCanal: "Viaje Barato",
    vistasPromedio: "20K-400K",
    tipo: "long", rank: 35,
  },
  {
    id: "emigrar-pais",
    nombre: "Emigrar a Otro País",
    categoria: "Viajes",
    rpmMin: 4, rpmMax: 10,
    gananciasMin: 400, gananciasMax: 1000,
    competencia: "baja", tendencia: "subiendo", faceless: false,
    idioma: "español",
    keywords: ["emigrar España", "vivir en el extranjero", "visa trabajo", "mudarse a otro país"],
    descripcion: "Guías para emigrar, obtener visas y establecerse en otro país.",
    ejemploCanal: "Emigra Conmigo",
    vistasPromedio: "20K-450K",
    tipo: "long", rank: 26,
  },
  {
    id: "nomada-digital",
    nombre: "Nómada Digital",
    categoria: "Viajes",
    rpmMin: 4, rpmMax: 11,
    gananciasMin: 400, gananciasMax: 1100,
    competencia: "baja", tendencia: "subiendo", faceless: false,
    idioma: "español",
    keywords: ["nómada digital", "trabajar viajando", "remote work", "vivir viajando"],
    descripcion: "Estilo de vida nómada digital: trabajar en línea mientras viajas por el mundo.",
    ejemploCanal: "Nómada Digital",
    vistasPromedio: "15K-350K",
    tipo: "long", rank: 21,
  },

  // HOGAR Y LIFESTYLE
  {
    id: "decoracion-hogar-nuevo",
    nombre: "Decoración del Hogar",
    categoria: "Hogar",
    rpmMin: 3, rpmMax: 7,
    gananciasMin: 300, gananciasMax: 700,
    competencia: "media", tendencia: "estable", faceless: false,
    idioma: "español",
    keywords: ["decorar casa", "ideas decoración", "sala comedor", "dormitorio bonito"],
    descripcion: "Ideas y tendencias de decoración del hogar para cada habitación.",
    ejemploCanal: "Casa Bonita",
    vistasPromedio: "15K-350K",
    tipo: "long", rank: 41,
  },
  {
    id: "minimalismo",
    nombre: "Minimalismo",
    categoria: "Hogar",
    rpmMin: 3, rpmMax: 7,
    gananciasMin: 300, gananciasMax: 700,
    competencia: "baja", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["minimalismo", "vida simple", "declutter", "menos es más", "capsule wardrobe"],
    descripcion: "Estilo de vida minimalista, organización del hogar y vida consciente.",
    ejemploCanal: "Vida Minimalista",
    vistasPromedio: "10K-250K",
    tipo: "long", rank: 46,
  },
  {
    id: "van-life",
    nombre: "Van Life / Tiny House",
    categoria: "Hogar",
    rpmMin: 3, rpmMax: 8,
    gananciasMin: 300, gananciasMax: 800,
    competencia: "baja", tendencia: "subiendo", faceless: false,
    idioma: "español",
    keywords: ["van life", "tiny house", "casas pequeñas", "furgoneta camper", "vida libre"],
    descripcion: "Vida en furgoneta, casas pequeñas y libertad de movimiento.",
    ejemploCanal: "Van Life España",
    vistasPromedio: "10K-300K",
    tipo: "long", rank: 40,
  },

  // ANIMALES
  {
    id: "perros-adiestramiento",
    nombre: "Perros y Adiestramiento",
    categoria: "Animales",
    rpmMin: 3, rpmMax: 7,
    gananciasMin: 300, gananciasMax: 700,
    competencia: "media", tendencia: "estable", faceless: false,
    idioma: "español",
    keywords: ["adiestramiento perros", "educar perro", "problemas conducta perro", "razas perros"],
    descripcion: "Adiestramiento canino, comportamiento y cuidados del perro.",
    ejemploCanal: "El Amaestrador",
    vistasPromedio: "20K-400K",
    tipo: "long", rank: 43,
  },
  {
    id: "gatos",
    nombre: "Gatos",
    categoria: "Animales",
    rpmMin: 2, rpmMax: 5,
    gananciasMin: 200, gananciasMax: 500,
    competencia: "alta", tendencia: "estable", faceless: false,
    idioma: "español",
    keywords: ["gatos", "comportamiento gatos", "cuidar gato", "razas de gatos"],
    descripcion: "Todo sobre gatos: comportamiento, cuidados, razas y curiosidades.",
    ejemploCanal: "Mundo Felino",
    vistasPromedio: "20K-500K",
    tipo: "ambos", rank: 55,
  },
  {
    id: "animales-exoticos",
    nombre: "Animales Exóticos",
    categoria: "Animales",
    rpmMin: 2, rpmMax: 6,
    gananciasMin: 200, gananciasMax: 600,
    competencia: "baja", tendencia: "subiendo", faceless: false,
    idioma: "español",
    keywords: ["animales exóticos", "reptiles mascotas", "animales raros", "fauna salvaje"],
    descripcion: "Fascinante mundo de los animales exóticos, reptiles y fauna salvaje.",
    ejemploCanal: "Animales Únicos",
    vistasPromedio: "15K-350K",
    tipo: "ambos", rank: 52,
  },

  // SHORTS ESPECÍFICOS
  {
    id: "shorts-datos-curiosos",
    nombre: "Shorts de Datos Curiosos",
    categoria: "Shorts",
    rpmMin: 1, rpmMax: 4,
    gananciasMin: 100, gananciasMax: 400,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["datos curiosos", "facts", "curiosidades", "sabías que", "shorts curiosidades"],
    descripcion: "Shorts virales con datos curiosos, hechos sorprendentes y curiosidades.",
    ejemploCanal: "FactsCortos",
    vistasPromedio: "100K-10M",
    tipo: "short", rank: 1,
  },
  {
    id: "shorts-motivacion",
    nombre: "Shorts de Motivación",
    categoria: "Shorts",
    rpmMin: 1, rpmMax: 4,
    gananciasMin: 100, gananciasMax: 400,
    competencia: "alta", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["motivación shorts", "frases motivadoras", "éxito rápido", "shorts inspiración"],
    descripcion: "Shorts motivacionales, frases de éxito y contenido inspirador.",
    ejemploCanal: "Motivación Diaria",
    vistasPromedio: "50K-5M",
    tipo: "short", rank: 2,
  },
  {
    id: "shorts-recetas",
    nombre: "Shorts de Recetas",
    categoria: "Shorts",
    rpmMin: 1, rpmMax: 3,
    gananciasMin: 100, gananciasMax: 300,
    competencia: "alta", tendencia: "estable", faceless: false,
    idioma: "español",
    keywords: ["recetas rápidas shorts", "cocina en 60 segundos", "receta viral", "comida fácil"],
    descripcion: "Recetas de cocina en formato short: rápido, visual y delicioso.",
    ejemploCanal: "Cocina Express",
    vistasPromedio: "50K-3M",
    tipo: "short", rank: 5,
  },
  {
    id: "shorts-fitness",
    nombre: "Shorts de Fitness",
    categoria: "Shorts",
    rpmMin: 1, rpmMax: 4,
    gananciasMin: 100, gananciasMax: 400,
    competencia: "alta", tendencia: "subiendo", faceless: false,
    idioma: "español",
    keywords: ["fitness shorts", "ejercicio 60 segundos", "abs shorts", "workout viral"],
    descripcion: "Ejercicios, rutinas y tips de fitness en formato short viral.",
    ejemploCanal: "Fit en Shorts",
    vistasPromedio: "50K-5M",
    tipo: "short", rank: 3,
  },
  {
    id: "shorts-idiomas",
    nombre: "Shorts de Idiomas",
    categoria: "Shorts",
    rpmMin: 1, rpmMax: 3,
    gananciasMin: 100, gananciasMax: 300,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["inglés en shorts", "frases en inglés", "vocabulario inglés", "aprender idioma rápido"],
    descripcion: "Aprende palabras y frases de idiomas en shorts divertidos.",
    ejemploCanal: "Idioma Shorts",
    vistasPromedio: "50K-2M",
    tipo: "short", rank: 7,
  },
  {
    id: "shorts-historia",
    nombre: "Shorts de Historia",
    categoria: "Shorts",
    rpmMin: 1, rpmMax: 3,
    gananciasMin: 100, gananciasMax: 300,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["historia en 60 segundos", "curiosidades históricas", "shorts historia", "hechos históricos"],
    descripcion: "Hechos históricos fascinantes resumidos en shorts entretenidos.",
    ejemploCanal: "Historia Rápida",
    vistasPromedio: "30K-2M",
    tipo: "short", rank: 9,
  },
  {
    id: "shorts-ciencia",
    nombre: "Shorts de Ciencia",
    categoria: "Shorts",
    rpmMin: 2, rpmMax: 5,
    gananciasMin: 200, gananciasMax: 500,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["ciencia shorts", "experimentos shorts", "física fácil", "biología curiosa"],
    descripcion: "Ciencia explicada de forma visual y divertida en formato short.",
    ejemploCanal: "Ciencia Viral",
    vistasPromedio: "50K-3M",
    tipo: "short", rank: 4,
  },
  {
    id: "shorts-virales-challenge",
    nombre: "Shorts Virales y Challenges",
    categoria: "Shorts",
    rpmMin: 1, rpmMax: 3,
    gananciasMin: 100, gananciasMax: 300,
    competencia: "alta", tendencia: "subiendo", faceless: false,
    idioma: "español",
    keywords: ["challenges virales", "trend tiktok", "reto viral", "shorts trending"],
    descripcion: "Challenges, retos virales y trends de TikTok y YouTube Shorts.",
    ejemploCanal: "Viral Challenge",
    vistasPromedio: "100K-10M",
    tipo: "short", rank: 6,
  },

  // GAMING (nuevos)
  {
    id: "minecraft-nuevo",
    nombre: "Minecraft Contenido",
    categoria: "Gaming",
    rpmMin: 1, rpmMax: 3,
    gananciasMin: 100, gananciasMax: 300,
    competencia: "alta", tendencia: "estable", faceless: true,
    idioma: "español",
    keywords: ["minecraft 2025", "minecraft builds", "minecraft survival", "minecraft mods"],
    descripcion: "Contenido variado de Minecraft: builds, survival, mods y servidores.",
    ejemploCanal: "Minecraft ES",
    vistasPromedio: "50K-2M",
    tipo: "ambos", rank: 16,
  },
  {
    id: "fortnite",
    nombre: "Fortnite",
    categoria: "Gaming",
    rpmMin: 1, rpmMax: 3,
    gananciasMin: 100, gananciasMax: 300,
    competencia: "alta", tendencia: "bajando", faceless: false,
    idioma: "español",
    keywords: ["fortnite", "fortnite gameplay", "fortnite tips", "battle royale"],
    descripcion: "Gameplay, tips y novedades de Fortnite battle royale.",
    ejemploCanal: "Fortnite España",
    vistasPromedio: "20K-500K",
    tipo: "short", rank: 20,
  },
  {
    id: "valorant",
    nombre: "Valorant",
    categoria: "Gaming",
    rpmMin: 1, rpmMax: 3,
    gananciasMin: 100, gananciasMax: 300,
    competencia: "alta", tendencia: "estable", faceless: false,
    idioma: "español",
    keywords: ["valorant", "valorant gameplay", "valorant tips", "clips valorant"],
    descripcion: "Clips, guías y contenido competitivo de Valorant.",
    ejemploCanal: "Valorant Clips",
    vistasPromedio: "20K-400K",
    tipo: "short", rank: 19,
  },
  {
    id: "gaming-retro-nuevo",
    nombre: "Gaming Retro Clásico",
    categoria: "Gaming",
    rpmMin: 2, rpmMax: 5,
    gananciasMin: 200, gananciasMax: 500,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["retro gaming", "SNES", "PS1", "juegos clásicos", "nostalgia videojuegos"],
    descripcion: "Análisis y nostalgia de videojuegos y consolas de los años 80 y 90.",
    ejemploCanal: "Retro Gamer ES",
    vistasPromedio: "10K-200K",
    tipo: "long", rank: 48,
  },
  {
    id: "reviews-videojuegos",
    nombre: "Reviews de Videojuegos",
    categoria: "Gaming",
    rpmMin: 2, rpmMax: 5,
    gananciasMin: 200, gananciasMax: 500,
    competencia: "alta", tendencia: "estable", faceless: false,
    idioma: "español",
    keywords: ["review videojuegos", "análisis juegos", "top mejores juegos", "reseñas gaming"],
    descripcion: "Reviews detallados y análisis de videojuegos para todas las plataformas.",
    ejemploCanal: "Analiza Gaming",
    vistasPromedio: "15K-300K",
    tipo: "long", rank: 47,
  },

  // CIENCIA Y TECNOLOGÍA
  {
    id: "fisica-cuantica",
    nombre: "Física Cuántica Explicada",
    categoria: "Ciencia",
    rpmMin: 4, rpmMax: 9,
    gananciasMin: 400, gananciasMax: 900,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["física cuántica", "mecánica cuántica", "universo paralelo", "relatividad"],
    descripcion: "Física cuántica y relatividad explicadas de forma accesible y fascinante.",
    ejemploCanal: "Cuántica Fácil",
    vistasPromedio: "20K-400K",
    tipo: "long", rank: 25,
  },
  {
    id: "astronomia",
    nombre: "Astronomía",
    categoria: "Ciencia",
    rpmMin: 3, rpmMax: 8,
    gananciasMin: 300, gananciasMax: 800,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["astronomía", "espacio", "agujeros negros", "NASA", "planetas"],
    descripcion: "Exploración del universo, agujeros negros, planetas y misiones espaciales.",
    ejemploCanal: "Cosmos Español",
    vistasPromedio: "20K-500K",
    tipo: "long", rank: 31,
  },
  {
    id: "ciencia-viral",
    nombre: "Ciencia Viral",
    categoria: "Ciencia",
    rpmMin: 3, rpmMax: 7,
    gananciasMin: 300, gananciasMax: 700,
    competencia: "media", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["ciencia viral", "experimentos caseros", "fenómenos naturales", "biología"],
    descripcion: "Ciencia explicada de forma viral, experimentos y fenómenos naturales.",
    ejemploCanal: "Ciencia Para Todos",
    vistasPromedio: "30K-1M",
    tipo: "ambos", rank: 33,
  },

  // ARTE Y CREATIVIDAD
  {
    id: "dibujo-ilustracion",
    nombre: "Dibujo e Ilustración",
    categoria: "Arte",
    rpmMin: 2, rpmMax: 5,
    gananciasMin: 200, gananciasMax: 500,
    competencia: "media", tendencia: "estable", faceless: false,
    idioma: "español",
    keywords: ["aprender dibujo", "ilustración digital", "Procreate", "dibujo anime", "sketching"],
    descripcion: "Tutoriales de dibujo, ilustración digital y arte para todos los niveles.",
    ejemploCanal: "Dibuja Conmigo",
    vistasPromedio: "15K-400K",
    tipo: "long", rank: 51,
  },
  {
    id: "diseno-grafico",
    nombre: "Diseño Gráfico",
    categoria: "Arte",
    rpmMin: 3, rpmMax: 7,
    gananciasMin: 300, gananciasMax: 700,
    competencia: "media", tendencia: "estable", faceless: false,
    idioma: "español",
    keywords: ["diseño gráfico", "Canva", "Adobe Illustrator", "branding", "logos"],
    descripcion: "Tutoriales de diseño gráfico, Canva, branding y creación de logos.",
    ejemploCanal: "Diseño Digital",
    vistasPromedio: "15K-300K",
    tipo: "long", rank: 39,
  },
  {
    id: "fotografia",
    nombre: "Fotografía",
    categoria: "Arte",
    rpmMin: 3, rpmMax: 7,
    gananciasMin: 300, gananciasMax: 700,
    competencia: "media", tendencia: "estable", faceless: false,
    idioma: "español",
    keywords: ["fotografía", "Lightroom", "edición fotos", "cámara DSLR", "fotografía móvil"],
    descripcion: "Técnicas fotográficas, edición en Lightroom y fotografía con móvil.",
    ejemploCanal: "Foto Fácil",
    vistasPromedio: "10K-200K",
    tipo: "long", rank: 45,
  },

  // FINANZAS ADICIONALES
  {
    id: "educacion-financiera",
    nombre: "Educación Financiera Juvenil",
    categoria: "Finanzas",
    rpmMin: 6, rpmMax: 14,
    gananciasMin: 600, gananciasMax: 1400,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["educación financiera jóvenes", "primer empleo dinero", "ahorrar con 20 años", "finanzas básicas"],
    descripcion: "Educación financiera para jóvenes: primeros pasos con el dinero y la inversión.",
    ejemploCanal: "Finanzas Jóvenes",
    vistasPromedio: "15K-300K",
    tipo: "long", rank: 14,
  },

  // SHORTS ADICIONAL
  {
    id: "shorts-finanzas",
    nombre: "Shorts de Finanzas",
    categoria: "Shorts",
    rpmMin: 2, rpmMax: 6,
    gananciasMin: 200, gananciasMax: 600,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["finanzas shorts", "tips dinero", "ahorro rápido", "inversión shorts"],
    descripcion: "Tips de finanzas personales, ahorro e inversión en formato short.",
    ejemploCanal: "Dinero Corto",
    vistasPromedio: "30K-2M",
    tipo: "short", rank: 11,
  },

  // TECNOLOGÍA ADICIONAL
  {
    id: "ciberseguridad",
    nombre: "Ciberseguridad",
    categoria: "Tecnología",
    rpmMin: 5, rpmMax: 13,
    gananciasMin: 500, gananciasMax: 1300,
    competencia: "baja", tendencia: "subiendo", faceless: true,
    idioma: "español",
    keywords: ["ciberseguridad", "hacking ético", "privacidad online", "VPN", "contraseñas seguras"],
    descripcion: "Ciberseguridad, privacidad digital y protección contra hackers explicada.",
    ejemploCanal: "Seguridad Digital",
    vistasPromedio: "10K-200K",
    tipo: "long", rank: 17,
  },
];

export const categorias = [...new Set(nichos.map((n) => n.categoria))].sort();
